### ISSUE TITLE
底部菜单栏"A-SOUL百科"图标和文字重叠

### ISSUE THREAD

**Issue by yllhwa** [jiangdashao/ASoulZhiWang#8]
### **屏幕分辨率:** 2400x1080  

![](https://user-images.githubusercontent.com/42028599/126639466-e46b4dcf-abe7-4d18-bfdf-b0f5e94599d2.jpg)

考虑到软件使用者大概率是au，也许可以省略“A-SOUL”，保留“百科”即可。

同时由于github近期在境内访问不稳定，百科内容经常加载失败。是否可以考虑使用jsdelivr或其他加速服务帮助境内au使用该服务？

**Comment by re-ovo** [comment]
好滴

**Comment by re-ovo** [comment]
好了捏
